[project]
name = 'BillSplit-Protocol'
description = 'A decentralized restaurant bill splitting platform on Stacks blockchain'
authors = ['DineChain Team']
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.BillSplitProtocol]
path = 'contracts/BillSplitProtocol.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
